name: Publish image

on:
  push:
    branches:
      - "release"
      - "main"
    paths-ignore:
      - README.md

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            osscompassorg/compass-echart-server
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'release') }}
            type=raw,value=nightly,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix={{branch}}-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
          password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SENTRY_DSN=${{secrets.SENTRY_DSN}}
            SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}}
            GIT_COMMIT=${{github.sha}}
